name: "Deploy Application"
description: "Deploys the application with all best practices"

inputs:
  environment:
    description: "Environment to deploy (dev or prd)"
    required: true
  ssh-key:
    description: "SSH private key"
    required: true
  vps-host:
    description: "VPS hostname"
    required: true
  vps-user:
    description: "VPS user"
    required: true

outputs:
  deploy-status:
    description: "Deploy status (success or failure)"
    value: ${{ steps.deploy.outputs.status }}
  deploy-time:
    description: "Deploy duration in seconds"
    value: ${{ steps.deploy.outputs.duration }}

runs:
  using: "composite"
  steps:
    - name: Deploy application
      id: deploy
      shell: bash
      run: |
        START_TIME=$SECONDS

        DEPLOY_OUTPUT=$(ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ inputs.vps-user }}@${{ inputs.vps-host }} "cd /home/deploy/gas-e-agua-backend && bash ./scripts/deploy/deploy.sh ${{ inputs.environment }} 2>&1")
        DEPLOY_EXIT_CODE=$?

        echo "$DEPLOY_OUTPUT"

        if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
          echo "❌ Deploy failed with exit code $DEPLOY_EXIT_CODE"
          exit 1
        fi

        DEPLOY_TIME=$((SECONDS - START_TIME))
        echo "status=success" >> $GITHUB_OUTPUT
        echo "duration=$DEPLOY_TIME" >> $GITHUB_OUTPUT
        echo "⏱️ Deploy completed in ${DEPLOY_TIME}s"
