# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: Deploy to VPS

# Quando esse workflow será executado
on:
  push:
    branches:
      - master # dispara após merge na master

jobs:
  deploy: # Nome do job
    runs-on: ubuntu-latest # O job rodará em uma máquina virtual Ubuntu

    steps:
      # Etapa 1: Fazer checkout (clonar) o código do repositório
      - name: Checkout code
        uses: actions/checkout@v3

      # Etapa 2: Configurar SSH para poder se conectar com o servidor VPS
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh  # Cria o diretório .ssh, se não existir

          # Salva a chave privada nas Actions Secrets em um arquivo chamado id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa

          chmod 600 ~/.ssh/id_rsa  # Garante que só o dono pode ler o arquivo (boa prática de segurança)

          # Adiciona a chave pública da VPS à lista de hosts conhecidos (evita prompts de confirmação SSH)
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      # Etapa 3: Conectar por SSH na VPS, fazer pull do código e reiniciar a aplicação
      - name: Pull latest code and restart app
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            cd /home/deploy/gas-e-agua-backend
            git fetch --all
            git checkout master
            git pull --ff-only
            docker compose -f docker-compose.app.yml up -d --build --remove-orphans
            docker compose -f docker-compose.monitoring-prd.yml up -d --remove-orphans
            docker system prune -f
          EOF
