name: 🔄 Rotate Secrets

on:
  schedule:
    # Roda no dia 1 de cada trimestre às 00:00 UTC (21:00 BRT do dia anterior)
    - cron: "0 0 1 1,4,7,10 *"

  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to rotate secrets"
        required: true
        type: choice
        options:
          - dev
          - prd
          - both
      force:
        description: "Force rotation even if not needed"
        required: false
        type: boolean
        default: false

jobs:
  rotate-dev:
    name: Rotate DEV Secrets
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'dev' || github.event.inputs.environment == 'both' || github.event_name == 'schedule'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate new secrets
        id: generate
        run: |
          echo "::group::🔑 Generating new secrets for DEV"

          # Funções para gerar secrets
          generate_password() {
            openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
          }

          generate_jwt() {
            openssl rand -hex 64
          }

          # Gerar novos secrets
          MYSQL_ROOT_PASSWORD=$(generate_password)
          MYSQL_PASSWORD=$(generate_password)
          JWT_SECRET=$(generate_jwt)
          GRAFANA_ADMIN_PASSWORD=$(generate_password)
          GRAFANA_SECRET_KEY=$(generate_password)

          # Exportar para próximos steps
          echo "mysql_root_password=$MYSQL_ROOT_PASSWORD" >> $GITHUB_OUTPUT
          echo "mysql_password=$MYSQL_PASSWORD" >> $GITHUB_OUTPUT
          echo "jwt_secret=$JWT_SECRET" >> $GITHUB_OUTPUT
          echo "grafana_admin_password=$GRAFANA_ADMIN_PASSWORD" >> $GITHUB_OUTPUT
          echo "grafana_secret_key=$GRAFANA_SECRET_KEY" >> $GITHUB_OUTPUT

          echo "✅ Secrets generated successfully"
          echo "::endgroup::"

      - name: Update GitHub Secrets
        env:
          GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "::group::📝 Updating GitHub Secrets"

          # Atualizar secrets via GitHub CLI
          gh secret set MYSQL_ROOT_PASSWORD_DEV --body "${{ steps.generate.outputs.mysql_root_password }}"
          gh secret set MYSQL_PASSWORD_DEV --body "${{ steps.generate.outputs.mysql_password }}"
          gh secret set JWT_SECRET_DEV --body "${{ steps.generate.outputs.jwt_secret }}"
          gh secret set GRAFANA_ADMIN_PASSWORD_DEV --body "${{ steps.generate.outputs.grafana_admin_password }}"
          gh secret set GRAFANA_SECRET_KEY_DEV --body "${{ steps.generate.outputs.grafana_secret_key }}"

          echo "✅ GitHub Secrets updated successfully"
          echo "::endgroup::"

      - name: Trigger deploy to apply new secrets
        run: |
          echo "::group::🚀 Triggering deploy"

          gh workflow run deploy-dev.yml \
            --ref ${{ github.ref_name }}

          echo "✅ Deploy triggered - secrets will be applied automatically"
          echo "::endgroup::"
        env:
          GH_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🔐 Secrets Rotated - DEV Environment"
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: GitHub Actions <noreply@github.com>
          html_body: |
            <!DOCTYPE html>
            <html>
            <head>
              <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: #4CAF50; color: white; padding: 20px; border-radius: 5px 5px 0 0; }
                .content { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; }
                .footer { background: #333; color: white; padding: 10px; text-align: center; border-radius: 0 0 5px 5px; }
                .alert { background: #fff3cd; border: 1px solid #ffc107; padding: 15px; margin: 20px 0; border-radius: 5px; }
                .success { background: #d4edda; border: 1px solid #28a745; }
                ul { list-style: none; padding: 0; }
                li { padding: 5px 0; }
                .icon { margin-right: 10px; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1>🔐 Secrets Rotation Completed</h1>
                </div>
                <div class="content">
                  <h2>Environment: DEV</h2>
                  <p><strong>Date:</strong> $(date -u +"%Y-%m-%d %H:%M:%S UTC")</p>
                  <p><strong>Triggered by:</strong> ${{ github.event_name == 'schedule' && 'Automatic Schedule' || 'Manual Trigger' }}</p>
                  
                  <div class="alert success">
                    <h3>✅ Rotated Secrets:</h3>
                    <ul>
                      <li>🔹 MYSQL_ROOT_PASSWORD_DEV</li>
                      <li>🔹 MYSQL_PASSWORD_DEV</li>
                      <li>🔹 JWT_SECRET_DEV</li>
                      <li>🔹 GRAFANA_ADMIN_PASSWORD_DEV</li>
                      <li>🔹 GRAFANA_SECRET_KEY_DEV</li>
                    </ul>
                  </div>
                  
                  <div class="alert">
                    <h3>⚠️ Important Information:</h3>
                    <ul>
                      <li><span class="icon">📝</span> <strong>JWT_SECRET:</strong> All active user sessions have been invalidated. Users will need to log in again.</li>
                      <li><span class="icon">🗄️</span> <strong>MySQL Password:</strong> Automatically updated in the database via deploy script.</li>
                      <li><span class="icon">🚀</span> <strong>Deploy:</strong> Automatically triggered to apply new secrets.</li>
                    </ul>
                  </div>
                  
                  <h3>📋 Next Steps:</h3>
                  <ol>
                    <li>Monitor the deploy workflow: <a href="${{ github.server_url }}/${{ github.repository }}/actions">Actions</a></li>
                    <li>Verify health check after deploy</li>
                    <li>Check for any authentication issues</li>
                  </ol>
                  
                  <p><strong>Workflow Run:</strong> <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">#${{ github.run_number }}</a></p>
                </div>
                <div class="footer">
                  <p>Gas e Água Backend - Automated Secrets Rotation</p>
                  <p>Repository: ${{ github.repository }}</p>
                </div>
              </div>
            </body>
            </html>

  rotate-prd:
    name: Rotate PRD Secrets
    runs-on: ubuntu-latest
    if: github.event.inputs.environment == 'prd' || github.event.inputs.environment == 'both'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate new secrets
        id: generate
        run: |
          echo "::group::🔑 Generating new secrets for PRD"

          generate_password() {
            openssl rand -base64 32 | tr -d "=+/" | cut -c1-32
          }

          generate_jwt() {
            openssl rand -hex 64
          }

          MYSQL_ROOT_PASSWORD=$(generate_password)
          MYSQL_PASSWORD=$(generate_password)
          JWT_SECRET=$(generate_jwt)
          GRAFANA_ADMIN_PASSWORD=$(generate_password)
          GRAFANA_SECRET_KEY=$(generate_password)

          echo "mysql_root_password=$MYSQL_ROOT_PASSWORD" >> $GITHUB_OUTPUT
          echo "mysql_password=$MYSQL_PASSWORD" >> $GITHUB_OUTPUT
          echo "jwt_secret=$JWT_SECRET" >> $GITHUB_OUTPUT
          echo "grafana_admin_password=$GRAFANA_ADMIN_PASSWORD" >> $GITHUB_OUTPUT
          echo "grafana_secret_key=$GRAFANA_SECRET_KEY" >> $GITHUB_OUTPUT

          echo "✅ Secrets generated successfully"
          echo "::endgroup::"

      - name: Update GitHub Secrets
        env:
          GH_TOKEN: ${{ secrets.GHCR_TOKEN }}
        run: |
          echo "::group::📝 Updating GitHub Secrets"

          gh secret set MYSQL_ROOT_PASSWORD_PRD --body "${{ steps.generate.outputs.mysql_root_password }}"
          gh secret set MYSQL_PASSWORD_PRD --body "${{ steps.generate.outputs.mysql_password }}"
          gh secret set JWT_SECRET_PRD --body "${{ steps.generate.outputs.jwt_secret }}"
          gh secret set GRAFANA_ADMIN_PASSWORD_PRD --body "${{ steps.generate.outputs.grafana_admin_password }}"
          gh secret set GRAFANA_SECRET_KEY_PRD --body "${{ steps.generate.outputs.grafana_secret_key }}"

          echo "✅ GitHub Secrets updated successfully"
          echo "::endgroup::"

      - name: Trigger deploy to apply new secrets
        run: |
          echo "::group::🚀 Triggering deploy"

          gh workflow run deploy-prd.yml \
            --ref master

          echo "✅ Deploy triggered - secrets will be applied automatically"
          echo "::endgroup::"
        env:
          GH_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Send email notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          secure: true
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "🔐 Secrets Rotated - PRODUCTION Environment ⚠️"
          to: ${{ secrets.NOTIFICATION_EMAIL }}
          from: GitHub Actions <noreply@github.com>
          priority: high
          html_body: |
            <!DOCTYPE html>
            <html>
            <head>
              <style>
                body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
                .container { max-width: 600px; margin: 0 auto; padding: 20px; }
                .header { background: #dc3545; color: white; padding: 20px; border-radius: 5px 5px 0 0; }
                .content { background: #f9f9f9; padding: 20px; border: 1px solid #ddd; }
                .footer { background: #333; color: white; padding: 10px; text-align: center; border-radius: 0 0 5px 5px; }
                .alert { background: #fff3cd; border: 1px solid #ffc107; padding: 15px; margin: 20px 0; border-radius: 5px; }
                .success { background: #d4edda; border: 1px solid #28a745; }
                .danger { background: #f8d7da; border: 1px solid #dc3545; }
                ul { list-style: none; padding: 0; }
                li { padding: 5px 0; }
                .icon { margin-right: 10px; }
              </style>
            </head>
            <body>
              <div class="container">
                <div class="header">
                  <h1>🔐 Secrets Rotation Completed - PRODUCTION</h1>
                </div>
                <div class="content">
                  <h2>Environment: PRODUCTION ⚠️</h2>
                  <p><strong>Date:</strong> $(date -u +"%Y-%m-%d %H:%M:%S UTC")</p>
                  <p><strong>Triggered by:</strong> ${{ github.event_name == 'schedule' && 'Automatic Schedule' || 'Manual Trigger' }}</p>
                  
                  <div class="alert success">
                    <h3>✅ Rotated Secrets:</h3>
                    <ul>
                      <li>🔹 MYSQL_ROOT_PASSWORD_PRD</li>
                      <li>🔹 MYSQL_PASSWORD_PRD</li>
                      <li>🔹 JWT_SECRET_PRD</li>
                      <li>🔹 GRAFANA_ADMIN_PASSWORD_PRD</li>
                      <li>🔹 GRAFANA_SECRET_KEY_PRD</li>
                    </ul>
                  </div>
                  
                  <div class="alert danger">
                    <h3>⚠️ CRITICAL - User Impact:</h3>
                    <ul>
                      <li><span class="icon">🚨</span> <strong>ALL USERS LOGGED OUT:</strong> JWT_SECRET changed - all active sessions invalidated.</li>
                      <li><span class="icon">📱</span> <strong>Mobile Apps:</strong> Users will need to log in again.</li>
                      <li><span class="icon">🌐</span> <strong>Web Sessions:</strong> All web sessions expired.</li>
                    </ul>
                  </div>
                  
                  <div class="alert">
                    <h3>📝 Automatic Actions:</h3>
                    <ul>
                      <li><span class="icon">🗄️</span> MySQL password automatically updated in database</li>
                      <li><span class="icon">🚀</span> Deploy triggered to apply new secrets</li>
                      <li><span class="icon">📊</span> Grafana admin password updated</li>
                    </ul>
                  </div>
                  
                  <h3>📋 Required Actions:</h3>
                  <ol>
                    <li><strong>URGENT:</strong> Monitor deploy workflow: <a href="${{ github.server_url }}/${{ github.repository }}/actions">Actions</a></li>
                    <li>Verify application health after deploy</li>
                    <li>Check error logs for authentication issues</li>
                    <li>Monitor user login rate (expect spike)</li>
                    <li>Notify support team about mass logout</li>
                  </ol>
                  
                  <p><strong>Workflow Run:</strong> <a href="${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}">#${{ github.run_number }}</a></p>
                </div>
                <div class="footer">
                  <p>Gas e Água Backend - Automated Secrets Rotation</p>
                  <p>Repository: ${{ github.repository }}</p>
                  <p><strong>Environment: PRODUCTION</strong></p>
                </div>
              </div>
            </body>
            </html>
